os: linux
dist: focal
arch: amd64
virt: vm
language: shell
branches:
  only:
   - deb
env:
    DEB_ARCH=armhf
    DEB_DISTRO=buster
addons:
  apt:
    packages:
      - devscripts
      - build-essential
      - sbuild
      - schroot
      - debootstrap
script:
  - sudo ./.travis.build.sh
  
after-script:
  - cat /srv/chroot/buster-armhf-sbuild/debootstrap/debootstrap.log

deploy:
  provider: script
  cleanup: false
  script: curl -F package:${DEB_NAME} https://${FURYGEM_TOKEN}@push.fury.io/${FURYGEM_NAME}
