os: linux
dist: focal
arch: amd64
virt: vm
language: shell
branches:
  only:
   - deb
env:
    DEB_ARCH=armhf
    DEB_DISTRO=buster
addons:
  apt:
    packages:
      - devscripts
      - build-essential
      - sbuild
      - schroot
      - debootstrap
      - qemu-user-static
script:
  - sudo ./.travis.build.sh

before-deploy:
  - echo ${DEB_NAME}
  
deploy:
  provider: script
  cleanup: false
  script: curl -F package:${DEB_NAME} https://${FURYGEM_TOKEN}@push.fury.io/${FURYGEM_NAME}
  on:
    branch: deb
