os: linux
dist: focal
arch: amd64
virt: vm
language: shell
branches:
  only:
   - deb
env:
    DEB_ARCH=armhf
    DEB_DISTRO=buster
addons:
  apt:
    packages:
      - devscripts
      - build-essential
      - sbuild
      - schroot
      - debootstrap
      - qemu-user-static
script:
  - sudo ./travis/travis-build.sh

deploy:
  provider: script
  skip_cleanup: true
  script: ./travis/travis-deploy.sh
  on:
    branch: deb
